prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@workspace/credentials/google_api_key.sql
@@workspace/credentials/moviedb_api_key.sql
@@workspace/remote_servers/www_googleapis_com_youtube_v3.sql
@@workspace/remote_servers/api_themoviedb_org_3_list.sql
@@application/shared_components/data_profiles/apex_youtube_videos.sql
@@application/shared_components/data_profiles/apex_youtube_channel.sql
@@application/shared_components/data_profiles/apex_youtube_play_list_item.sql
@@application/shared_components/data_profiles/movie_database.sql
@@application/shared_components/web_sources/apex_youtube_videos.sql
@@application/shared_components/web_sources/apex_youtube_playlists.sql
@@application/shared_components/web_sources/apex_youtube_play_list_items.sql
@@application/shared_components/web_sources/movie_database.sql
@@application/shared_components/navigation/lists/advanced.sql
@@application/shared_components/navigation/lists/basics.sql
@@application/shared_components/navigation/lists/images_and_media.sql
@@application/shared_components/navigation/lists/card_actions.sql
@@application/shared_components/navigation/lists/home.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/page_navigation.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_sample_cards_ico.sql
@@application/shared_components/files/app_sample_cards_16x16_png.sql
@@application/shared_components/files/app_sample_cards_32x32_png.sql
@@application/shared_components/files/app_sample_cards_png.sql
@@application/shared_components/files/apex_mountain_range_light_png.sql
@@application/shared_components/files/app_icon_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/dept_dname.sql
@@application/shared_components/user_interface/lovs/emp_mgr.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/bare.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_vehicle_speed.sql
@@application/deployment/install/install_random_image.sql
@@application/deployment/install/install_emp_dept_tables.sql
@@application/deployment/install/install_load_dept_data.sql
@@application/deployment/install/install_emp_king.sql
@@application/deployment/install/install_emp_blake.sql
@@application/deployment/install/install_emp_thea.sql
@@application/deployment/install/install_emp_wei.sql
@@application/deployment/install/install_emp_allen.sql
@@application/deployment/install/install_emp_diana.sql
@@application/deployment/install/install_emp_jones.sql
@@application/deployment/install/install_emp_sarita.sql
@@application/deployment/install/install_emp_susan.sql
@@application/deployment/install/install_emp_martin.sql
@@application/deployment/install/install_emp_mee.sql
@@application/deployment/install/install_emp_james.sql
@@application/deployment/install/install_emp_adams.sql
@@application/deployment/install/install_emp_sari.sql
@@application/deployment/install/install_eba_demo_card_pkg.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
