prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@workspace/credentials/credentials_for_gpt_5_mini.sql
@@workspace/credentials/app_104_push_notifications_credentials.sql
@@workspace/remote_servers/gpt_5_mini.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/boolean.sql
@@application/shared_components/user_interface/lovs/wwv_credentials_name.sql
@@application/shared_components/user_interface/lovs/wwv_flows_alias.sql
@@application/shared_components/user_interface/lovs/wwv_flow_companies_short_name.sql
@@application/shared_components/user_interface/lovs/wwv_purge_workspaces_workspace_name.sql
@@application/shared_components/user_interface/lovs/wwv_purge_workspaces_workspace_name_1.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_09999.sql
@@application/pages/page_20000.sql
@@application/pages/page_20010.sql
@@application/end_environment.sql
