prompt --application/shared_components/user_interface/lovs/aggregate_functions
begin
--   Manifest
--     AGGREGATE_FUNCTIONS
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(101016778607432389)
,p_lov_name=>'AGGREGATE_FUNCTIONS'
,p_static_id=>'aggregate-functions'
,p_lov_query=>'.'||wwv_flow_imp.id(101016778607432389)||'.'
,p_location=>'STATIC'
,p_version_scn=>'SH256:S-vjlWqL3jNsI2VbWg2cPZBJtAt5vY2PgvCfoRsBkW4'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(101017392766432406)
,p_lov_disp_sequence=>10
,p_lov_disp_value=>'Count'
,p_lov_return_value=>'COUNT'
,p_static_id=>'count'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(155331225296971782)
,p_lov_disp_sequence=>20
,p_lov_disp_value=>'Count Distinct'
,p_lov_return_value=>'COUNT_DISTINCT'
,p_static_id=>'count-distinct'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(155331592721974019)
,p_lov_disp_sequence=>30
,p_lov_disp_value=>'Approx. Count Distinct'
,p_lov_return_value=>'APPROX_COUNT_DISTINCT'
,p_static_id=>'approx-count-distinct'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(155331898423975434)
,p_lov_disp_sequence=>40
,p_lov_disp_value=>'Minimum'
,p_lov_return_value=>'MIN'
,p_static_id=>'min'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(155332158908977182)
,p_lov_disp_sequence=>50
,p_lov_disp_value=>'Maximum'
,p_lov_return_value=>'MAX'
,p_static_id=>'max'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(101017723584432406)
,p_lov_disp_sequence=>60
,p_lov_disp_value=>'Sum'
,p_lov_return_value=>'SUM'
,p_static_id=>'sum'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(155335855601993887)
,p_lov_disp_sequence=>70
,p_lov_disp_value=>'Average'
,p_lov_return_value=>'AVG'
,p_static_id=>'avg'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(166230555723037356)
,p_lov_disp_sequence=>80
,p_lov_disp_value=>'Median'
,p_lov_return_value=>'MEDIAN'
,p_static_id=>'median'
);
wwv_flow_imp.component_end;
end;
/
