prompt --application/shared_components/user_interface/lovs/condition_control_type
begin
--   Manifest
--     CONDITION CONTROL TYPE
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(179476200494904933)
,p_lov_name=>'CONDITION CONTROL TYPE'
,p_static_id=>'condition-control-type'
,p_lov_query=>'.'||wwv_flow_imp.id(179476200494904933)||'.'
,p_location=>'STATIC'
,p_version_scn=>'SH256:LJJL1dnMr10OXJVaUvgGpsb9n3ef3gy4C8LbD0kX_UU'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179477608235904943)
,p_lov_disp_sequence=>1
,p_lov_disp_value=>'Branch'
,p_lov_return_value=>'BRANCH'
,p_static_id=>'branch'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179492924267978066)
,p_lov_disp_sequence=>2
,p_lov_disp_value=>'Button'
,p_lov_return_value=>'BUTTON'
,p_static_id=>'button'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179477001828904942)
,p_lov_disp_sequence=>3
,p_lov_disp_value=>'Computation'
,p_lov_return_value=>'COMPUTATION'
,p_static_id=>'computation'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179476801795904940)
,p_lov_disp_sequence=>4
,p_lov_disp_value=>'Item'
,p_lov_return_value=>'ITEM'
,p_static_id=>'item'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179477429719904942)
,p_lov_disp_sequence=>5
,p_lov_disp_value=>'Process'
,p_lov_return_value=>'PROCESS'
,p_static_id=>'process'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179476625958904939)
,p_lov_disp_sequence=>6
,p_lov_disp_value=>'Region'
,p_lov_return_value=>'REGION'
,p_static_id=>'region'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(179477227849904942)
,p_lov_disp_sequence=>7
,p_lov_disp_value=>'Validation'
,p_lov_return_value=>'VALIDATION'
,p_static_id=>'validation'
);
wwv_flow_imp.component_end;
end;
/
