prompt --application/shared_components/user_interface/lovs/data_load_csv_col_delimiter
begin
--   Manifest
--     DATA.LOAD.CSV_COL_DELIMITER
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(1963861252255121)
,p_lov_name=>'DATA.LOAD.CSV_COL_DELIMITER'
,p_static_id=>'data-load-csv-col-delimiter'
,p_lov_query=>'.'||wwv_flow_imp.id(1963861252255121)||'.'
,p_location=>'STATIC'
,p_version_scn=>'SH256:LyOdoWoOqWrBXlNWspPJUntqvKh3KgQG6lAAZUrUw4A'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1964152277255145)
,p_lov_disp_sequence=>20
,p_lov_disp_value=>','
,p_lov_return_value=>','
,p_static_id=>','
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1964578744255147)
,p_lov_disp_sequence=>30
,p_lov_disp_value=>';'
,p_lov_return_value=>';'
,p_static_id=>';'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1964926636255147)
,p_lov_disp_sequence=>40
,p_lov_disp_value=>'|'
,p_lov_return_value=>'|'
,p_static_id=>'|'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1965387007255150)
,p_lov_disp_sequence=>60
,p_lov_disp_value=>'#'
,p_lov_return_value=>'#'
,p_static_id=>'#'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1965775882255150)
,p_lov_disp_sequence=>70
,p_lov_disp_value=>'tab'
,p_lov_return_value=>'tab'
,p_static_id=>'tab'
);
wwv_flow_imp.component_end;
end;
/
