prompt --application/shared_components/user_interface/lovs/dq_rpt_functionality
begin
--   Manifest
--     DQ_RPT_FUNCTIONALITY
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(93890902683872023)
,p_lov_name=>'DQ_RPT_FUNCTIONALITY'
,p_static_id=>'dq-rpt-functionality'
,p_lov_query=>'.'||wwv_flow_imp.id(93890902683872023)||'.'
,p_location=>'STATIC'
,p_version_scn=>'SH256:LB76i8h4LyUFTI2TYYUu_5xKx4RPChfcGLgrLXEf9So'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93891207939872035)
,p_lov_disp_sequence=>10
,p_lov_disp_value=>'Select Columns'
,p_lov_return_value=>'SELECT_COLS'
,p_static_id=>'select-cols'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93891430852872035)
,p_lov_disp_sequence=>20
,p_lov_disp_value=>'Filter'
,p_lov_return_value=>'FILTER'
,p_static_id=>'filter'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(445491215210900584)
,p_lov_disp_sequence=>30
,p_lov_disp_value=>'Rows Per Page'
,p_lov_return_value=>'ROWS_PER_PAGE'
,p_static_id=>'rows-per-page'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93891616940872035)
,p_lov_disp_sequence=>40
,p_lov_disp_value=>'Sort'
,p_lov_return_value=>'SORT'
,p_static_id=>'sort'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(141674418886754015)
,p_lov_disp_sequence=>50
,p_lov_disp_value=>'Control Break'
,p_lov_return_value=>'BREAK'
,p_static_id=>'break'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93891825853872035)
,p_lov_disp_sequence=>60
,p_lov_disp_value=>'Highlight'
,p_lov_return_value=>'HIGHLIGHT'
,p_static_id=>'highlight'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93893009214872050)
,p_lov_disp_sequence=>70
,p_lov_disp_value=>'Compute'
,p_lov_return_value=>'COMPUTATION'
,p_static_id=>'computation'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93892010217872035)
,p_lov_disp_sequence=>80
,p_lov_disp_value=>'Aggregate'
,p_lov_return_value=>'AGGREGATE'
,p_static_id=>'aggregate'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(96144107239525391)
,p_lov_disp_sequence=>90
,p_lov_disp_value=>'Chart'
,p_lov_return_value=>'CHART'
,p_static_id=>'chart'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(1541019690680918)
,p_lov_disp_sequence=>100
,p_lov_disp_value=>'Group By'
,p_lov_return_value=>'GROUP_BY'
,p_static_id=>'group-by'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(367023902558041646)
,p_lov_disp_sequence=>105
,p_lov_disp_value=>'Pivot'
,p_lov_return_value=>'PIVOT'
,p_static_id=>'pivot'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93892230261872036)
,p_lov_disp_sequence=>110
,p_lov_disp_value=>'Calendar'
,p_lov_return_value=>'CALENDAR'
,p_static_id=>'calendar'
,p_lov_disp_cond_type=>'NEVER'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93892430175872036)
,p_lov_disp_sequence=>110
,p_lov_disp_value=>'Flashback'
,p_lov_return_value=>'FLASHBACK'
,p_static_id=>'flashback'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(480714630007218066)
,p_lov_disp_sequence=>120
,p_lov_disp_value=>'Save Report *'
,p_lov_return_value=>'RPT_SAVING'
,p_static_id=>'rpt-saving'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(480714802780219726)
,p_lov_disp_sequence=>130
,p_lov_disp_value=>'Save Public Report *'
,p_lov_return_value=>'SAVE_RPT_PUBLIC'
,p_static_id=>'save-rpt-public'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93892610127872036)
,p_lov_disp_sequence=>140
,p_lov_disp_value=>'Reset'
,p_lov_return_value=>'RESET'
,p_static_id=>'reset'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(135686220155392741)
,p_lov_disp_sequence=>150
,p_lov_disp_value=>'Help'
,p_lov_return_value=>'HELP'
,p_static_id=>'help'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93892800927872050)
,p_lov_disp_sequence=>160
,p_lov_disp_value=>'Download'
,p_lov_return_value=>'DOWNLOAD'
,p_static_id=>'download'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(480715008321221245)
,p_lov_disp_sequence=>170
,p_lov_disp_value=>'Subscription *'
,p_lov_return_value=>'NOTIFY'
,p_static_id=>'notify'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(93893414283872050)
,p_lov_disp_sequence=>180
,p_lov_disp_value=>'Allow Report Categories'
,p_lov_return_value=>'RPT_CATEGORY'
,p_static_id=>'rpt-category'
,p_lov_disp_cond_type=>'NEVER'
);
wwv_flow_imp.component_end;
end;
/
