prompt --application/shared_components/user_interface/lovs/export_types
begin
--   Manifest
--     EXPORT_TYPES
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(84313028848586180)
,p_lov_name=>'EXPORT_TYPES'
,p_static_id=>'export-types'
,p_lov_query=>'.'||wwv_flow_imp.id(84313028848586180)||'.'
,p_location=>'STATIC'
,p_version_scn=>'SH256:QwYqWlo4IennPhb03OfMqgwPkT0215EZ967k2H6d0RE'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84313210243586181)
,p_lov_disp_sequence=>10
,p_lov_disp_value=>'Workspaces'
,p_lov_return_value=>'COMPANY_EXPORT'
,p_static_id=>'company-export'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84313400691586181)
,p_lov_disp_sequence=>20
,p_lov_disp_value=>'Applications'
,p_lov_return_value=>'FLOW_EXPORT'
,p_static_id=>'flow-export'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84313629140586181)
,p_lov_disp_sequence=>30
,p_lov_disp_value=>'Pages'
,p_lov_return_value=>'PAGE_EXPORT'
,p_static_id=>'page-export'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(30460601502095997)
,p_lov_disp_sequence=>35
,p_lov_disp_value=>'Plug-in'
,p_lov_return_value=>'PLUGIN'
,p_static_id=>'plugin'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84313822161586182)
,p_lov_disp_sequence=>40
,p_lov_disp_value=>'CSS'
,p_lov_return_value=>'CSS_EXPORT'
,p_static_id=>'css-export'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84314021666586182)
,p_lov_disp_sequence=>50
,p_lov_disp_value=>'Images'
,p_lov_return_value=>'IMAGE_EXPORT'
,p_static_id=>'image-export'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84314231797586182)
,p_lov_disp_sequence=>60
,p_lov_disp_value=>'Files'
,p_lov_return_value=>'FILE_EXPORT'
,p_static_id=>'file-export'
,p_lov_disp_cond_type=>'NEVER'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(84314413534586182)
,p_lov_disp_sequence=>70
,p_lov_disp_value=>'Scripts'
,p_lov_return_value=>'SCRIPT_FILE_EXPORT'
,p_static_id=>'script-file-export'
,p_lov_disp_cond_type=>'NEVER'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(218848421565947069)
,p_lov_disp_sequence=>75
,p_lov_disp_value=>'Static File Export'
,p_lov_return_value=>'FILE_EXPORT'
,p_static_id=>'file-export-2'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(217881026720006951)
,p_lov_disp_sequence=>80
,p_lov_disp_value=>'Themes'
,p_lov_return_value=>'THEME'
,p_static_id=>'theme'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(217881302263009316)
,p_lov_disp_sequence=>90
,p_lov_disp_value=>'UI Defaults'
,p_lov_return_value=>'UI_DEFAULTS'
,p_static_id=>'ui-defaults'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(39083219682790387)
,p_lov_disp_sequence=>100
,p_lov_disp_value=>'Team Development Feedback'
,p_lov_return_value=>'FEEDBACK'
,p_static_id=>'feedback'
);
wwv_flow_imp_shared.create_static_lov_data(
 p_id=>wwv_flow_imp.id(3931071348171445)
,p_lov_disp_sequence=>110
,p_lov_disp_value=>'REST Source Catalog'
,p_lov_return_value=>'CATALOG'
,p_static_id=>'catalog'
);
wwv_flow_imp.component_end;
end;
/
