prompt --application/shared_components/navigation/lists/deployment_tabs
begin
--   Manifest
--     LIST: deployment tabs
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list(
 p_id=>wwv_flow_imp.id(22452018965176093)
,p_name=>'deployment tabs'
,p_static_id=>'deployment-tabs'
,p_version_scn=>'SH256:oJ7gWEI0p-P9v6Wbzg9T1iYjhRbVucso1vLW36It7XA'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22452810092182983)
,p_list_item_display_sequence=>1
,p_list_item_link_text=>'Messages'
,p_static_id=>'Messages'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_567'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'567'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22521803109426954)
,p_list_item_display_sequence=>2
,p_list_item_link_text=>'Prerequisites'
,p_static_id=>'Prerequisites'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_631'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'631'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22503614097373329)
,p_list_item_display_sequence=>3
,p_list_item_link_text=>'Substitutions'
,p_static_id=>'Substitutions'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_17'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'17'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22516317738412258)
,p_list_item_display_sequence=>4
,p_list_item_link_text=>'Build Options'
,p_static_id=>'Build-Options'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_511'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'511'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22484008809315095)
,p_list_item_display_sequence=>7
,p_list_item_link_text=>'Validations'
,p_static_id=>'Validations'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_445'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'445'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22468026031263279)
,p_list_item_display_sequence=>10
,p_list_item_link_text=>'Install'
,p_static_id=>'Install'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_473'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'473'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(23543014930276179)
,p_list_item_display_sequence=>20
,p_list_item_link_text=>'Upgrade'
,p_static_id=>'Upgrade'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_667'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'667'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22498325263357607)
,p_list_item_display_sequence=>50
,p_list_item_link_text=>'Deinstall'
,p_static_id=>'Deinstall'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_576'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'576,579'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(22452401088180364)
,p_list_item_display_sequence=>90
,p_list_item_link_text=>'Export'
,p_static_id=>'Export'
,p_list_item_link_target=>'javascript:doSubmit(''APPLY_CHANGES_633'')'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'633'
);
wwv_flow_imp.component_end;
end;
/
