prompt --application/shared_components/navigation/lists/export_options
begin
--   Manifest
--     LIST: Export_options
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2099.99.99'
,p_release=>'25.1.0'
,p_default_workspace_id=>10
,p_default_application_id=>4000
,p_default_id_offset=>0
,p_default_owner=>'APEX_250100'
);
wwv_flow_imp_shared.create_list(
 p_id=>wwv_flow_imp.id(12802829107)
,p_name=>'Export_options'
,p_static_id=>'export-options'
,p_version_scn=>'SH256:8GST3d4nmd3NNp965HJCSC5XcpFvV2vMfkRHqF3yNX4'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(45716606101005971)
,p_list_item_display_sequence=>30
,p_list_item_link_text=>'Application'
,p_static_id=>'Application'
,p_list_item_link_target=>'f?p=&APP_ID.:4900:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'4900'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(6205783903288710)
,p_list_item_display_sequence=>40
,p_list_item_link_text=>'Page'
,p_static_id=>'Page'
,p_list_item_link_target=>'f?p=&APP_ID.:164:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'164'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(6206059937291623)
,p_list_item_display_sequence=>50
,p_list_item_link_text=>'Components'
,p_static_id=>'Components'
,p_list_item_link_target=>'f?p=&APP_ID.:688:&SESSION.::&DEBUG.:CR:::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'688'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(60513615035446206)
,p_list_item_display_sequence=>60
,p_list_item_link_text=>'Themes'
,p_static_id=>'Themes'
,p_list_item_link_target=>'f?p=&FLOW_ID.:224:&SESSION.::&DEBUG.:::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'224'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(30477123909319995)
,p_list_item_display_sequence=>70
,p_list_item_link_text=>'Plug-ins'
,p_static_id=>'Plug-ins'
,p_list_item_link_target=>'f?p=&APP_ID.:4460:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'4460'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(189447213907433212)
,p_list_item_display_sequence=>75
,p_list_item_link_text=>'XML Export and Reporting'
,p_static_id=>'XML-Export-and-Reporting'
,p_list_item_link_target=>'f?p=4850:1:&SESSION.'
,p_list_item_disp_cond_type=>'NEVER'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(145288215599412878)
,p_list_item_display_sequence=>80
,p_list_item_link_text=>'UI Defaults'
,p_static_id=>'UI-Defaults'
,p_list_item_link_target=>'f?p=&APP_ID.:479:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'479,541'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(472191226795751981)
,p_list_item_display_sequence=>90
,p_list_item_link_text=>'Feedback'
,p_static_id=>'Feedback'
,p_list_item_link_target=>'f?p=&APP_ID.:689:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'689'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(3743275033992392)
,p_list_item_display_sequence=>100
,p_list_item_link_text=>'Catalog'
,p_static_id=>'Catalog'
,p_list_item_link_target=>'f?p=&APP_ID.:1965:&SESSION.::&DEBUG.::::'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_imp_shared.create_list_item(
 p_id=>wwv_flow_imp.id(10804139761201725)
,p_list_item_display_sequence=>110
,p_list_item_link_text=>'Workspace'
,p_static_id=>'Workspace'
,p_list_item_link_target=>'f?p=&APP_ID.:76:&SESSION.::&DEBUG.::::'
,p_security_scheme=>wwv_flow_imp.id(12511519296310366)
,p_list_item_current_type=>'COLON_DELIMITED_PAGE_LIST'
,p_list_item_current_for_pages=>'76'
);
wwv_flow_imp.component_end;
end;
/
